# Generated by Django 5.2.5 on 2025-12-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_answeromr'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOmr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField()),
                ('images', models.JSONField(blank=True, default=list)),
                ('answer', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student_omr',
            },
        ),
    ]
