# Generated by Django 5.2.9 on 2025-12-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_studentomr'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeromr',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
