# Generated by Django 5.2.9 on 2025-12-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_answeromr_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeromr',
            name='exam_id',
            field=models.IntegerField(default=0),
        ),
    ]
