# Generated by Django 5.2.9 on 2025-12-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_answeromr_exam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeromr',
            name='exam_id',
            field=models.IntegerField(),
        ),
    ]
