# Generated by Django 5.2.9 on 2025-12-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_answeromr_exam_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentomr',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='studentomr',
            name='images',
        ),
        migrations.AddField(
            model_name='studentomr',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student_omr/'),
        ),
        migrations.AlterField(
            model_name='studentomr',
            name='answer',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
